### ISSUE TITLE
Compatible with .NET Core

### ISSUE THREAD

**Issue by mpaul31** [rebus-org/Topper#3]
is it possible for this package to be updated?

**Comment by mookid8000** [comment]
Yes, definitely – my initial worry was that [Topshelf](https://github.com/Topshelf/Topshelf) (which is responsible for Topper's abilities to be installed and run as a Windows Service) was only available on .NET 4.5.2, but since [Topshelf 4.0.4.148-develop](https://www.nuget.org/packages/Topshelf/4.0.4.148-develop) it seems the prereleases have support for .NET Standard 2.0.

It should be fairly easy to port it to Topshelf's prerelease package. Then [Topshelf.LibLog](https://www.nuget.org/packages/Topshelf.LibLog) only needs to follow along.

**Comment by mpaul31** [comment]
i failed hard trying to do this. having trouble finding a walk through. any hints or anyone else able to pitch in would be greatly appreciated. i'll keep at it.

**Comment by runes83** [comment]
Any update?

**Comment by mookid8000** [comment]
Topper 3.0.0 targets .NET Standard 2.0.

This means that it works with .NET Core 2 and .NET 4.6.2
